spring:
  application:
    name: hotel-soa-consumer-fegin-hytrix
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/
server:
  port: 9106
management:
  endpoints:
    web:
      exposure:
#        include: turbine.stream
        include: hystrix.stream
feign:
  hystrix:
    enabled: true